### ISSUE TITLE
Using .col file for Chroma81

### ISSUE THREAD

**Issue by Darknior** [libretro/81-libretro#19]
Hi

Some games are already code for Chroma 81 and works fine.
But many other are not and we can only found a .col file to put with the .p game.
The problem is that the emulator not using them to color the game :(

Will you add this feature please ?
Thanks

**Comment by Darknior** [comment]
Sorry i found the solution alone, i include the COL files i P files with this software.
http://www.fruitcake.plus.com/Sinclair/ZX81/Chroma/ChromaInterface_Software_ColourisationGeneratorLinux.htm
It works really fine. If it can help an other one ...

**Comment by leiradel** [comment]
This is what I used to create the colorized games available [here](https://github.com/libretro/81-libretro/tree/master/colorized).
